#!/usr/bin/env bash

export vREPODIR="/root/local-repos/binsync"

# Autofilled Variables (do not change)
export vPWD=$(pwd)
export vPATH=$(echo $PATH)

# Get calling script's directory
SOURCE=${BASH_SOURCE[0]}
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )
  SOURCE=$(readlink "$SOURCE")
  [[ $SOURCE != /* ]] && SOURCE=$DIR/$SOURCE # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
vSOURCEDIR=$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )

export vVER=$(cat ${vPWD}/.binsync.version)

if test -f "${vPWD}/.binsync.config"; then
  source ${vPWD}/.binsync.config
else
  echo "${vPWD}/.binsync.config does not exist, please read the README.md!"
  echo ""
  exit
fi

echo ""
echo "binsync-push ${vVER} [${vDIRECTORY}]"
echo ""
echo "user                [$vUSER]"
echo "host                [$vHOST]"
echo "source directory    [$vSOURCEDIR]"
echo "working directory   [$vPWD]"
echo "binsync directory   [$vPATH]"
echo "bin directory       [$vDIRECTORY]"
echo ""

rsync -u -d -p -E -z -v --delete --exclude=.* ${vDIRECTORY}/ ${vUSER}@${vHOST}:${vDIRECTORY}

# Clear ENV vars for security
source ${vSOURCEDIR}/.binsync.config.clear
