#!/usr/bin/env bash

echo ""
echo "binsync-push ${vDIRECTORY}"
echo ""

PWD=$(pwd)
if test -f "${PWD}/.binsync.config"; then
  source ${PWD}/.binsync.config
else
  echo "${PWD}/.binsync.config does not exist, please read the README.md!"
  echo ""
  exit
fi

rsync -a ${vDIRECTORY} ${vUSER}@${vHOST}:${vDIRECTORY}

# Clear ENV vars for security
source ${PWD}/config.clear.inc
