#!/usr/bin/env bash

echo ""
echo "binsync-pull ${vDIRECTORY}"
echo ""

PWD=$(pwd)
if test -f "${PWD}/.binsync.config"; then
  source ${PWD}/.binsync.config
else
  echo "${PWD}/.binsync.config does not exist, please read the README.md!"
  echo ""
  exit
fi

rsync -a ${vUSER}@${vHOST}:${vDIRECTORY} ${vDIRECTORY}

# Clear ENV vars for security
source ${PWD}/.binsync.config.clear
